spring:
  profiles:
    active: local
server:
  port: 8081

# local
---
spring:
  profiles: local
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/spring-boot-demo
    username: sa
    password:
    driver-class-name: org.h2.Driver


# development
---
spring:
  profiles: development
  flyway:
    enabled: false

# production
---
spring:
  profiles: production
  flyway:
    enabled: false








